http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: '*' #call host ngrock: Example 192.168.100.99,.... 
    paths: '*' #all path
serviceEndpoints:
  sap-api:
    url: 'http://192.168.100.30:3000' #redirect to host local
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sap-api 
              changeOrigin: true
